In [1]:
import pandas as pd

In [2]:
url = "https://www.nps.gov/articles/000/historic-listing-of-nps-park-codes.htm"

tables = pd.read_html(url)
len(tables)

1

In [3]:
df = tables[0]
df.head()

                                                   0           1
0                      Park, Program, or Office Name  Alpha Code
1  Abraham Lincoln Birthplace National Historical...        ABLI
2             Abraham Lincoln National Heritage Area     See MWR
3                               Acadia National Park        ACAD
4               Adams Memorial, District of Columbia     See NCR

In [4]:
df.columns = df.iloc[0]
df = df.iloc[1:].reset_index(drop=True)
df.head()

0                      Park, Program, or Office Name Alpha Code
0  Abraham Lincoln Birthplace National Historical...       ABLI
1             Abraham Lincoln National Heritage Area    See MWR
2                               Acadia National Park       ACAD
3               Adams Memorial, District of Columbia    See NCR
4                     Adams National Historical Park       ADAM

In [5]:
df.to_csv('park_names.csv', index=False)